[package]
name = "cryptopalsrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
base64 = "0.21.0"
openssl = "0.10.4"
aes = "0.8.2"
